n = input('Digite um valor: ')
# print('é letra? ' + str(n.isalpha()))
# print('tipo: '+ str(type(n)))
# print('é número? '+ str(n.isnumeric()))
# print('é maiúsculo? ' + str(n.isupper()))
# print('é minúsculo? ' + str(n.islower()))
print(f'é letra? {n.isalpha()}')
print(f'tipo: {type(n)}')
print(f'é número? {n.isnumeric()}')
print(f'é maiúsculo? {n.isupper()}')
print(f'é minúsculo? {n.islower()}')

